### ISSUE TITLE
redirect_uri is always set to localhost:8080

### ISSUE THREAD

**Issue by pandeybk** [MatrixCrawler/grails-spring-security-oauth2-facebook#1]
https://www.facebook.com/v2.6/dialog/oauth?scope=email&response_type=code&client_id=211212121212&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Foauth2%2Ffacebook%2Fcallback&state=facebook-secret-212121

Redirect url is always set to localhost:8080 causing trouble in production.

My config.

```
grails:
    plugin:
        springsecurity:
            oauth2:
                providers:
                    oauth2:
                        active: true
                        registration:
                            askToLinkOrCreateAccountUri: '/oauth2/ask'
                            roleNames: ['ROLE_USER']
                    facebook:
                        api_key: '32313123123'                          #needed
                        api_secret: '331321321321312'      #needed
                        successUri: "/oauth2/facebook/success"              #optional
                        failureUri: "/oauth2/facebook/failure"              #optional
                        callback: "/oauth2/facebook/callback"               #optional
```
